service: my-service

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  app:
    handler: ./server/handler.server
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

custom:
  serverless-offline:
    httpPort: 4000
    prefix: ''
